


















.build/mega2560/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/mega2560/arduino/wiring.d

.build/mega2560/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/mega2560/arduino/wiring_digital.d

.build/mega2560/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/mega2560/arduino/wiring_analog.d

.build/mega2560/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/mega2560/arduino/WInterrupts.d

.build/mega2560/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/mega2560/arduino/wiring_pulse.d

.build/mega2560/arduino/avr-libc/malloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/mega2560/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/mega2560/arduino/avr-libc/malloc.d

.build/mega2560/arduino/avr-libc/realloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/mega2560/arduino/avr-libc
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/mega2560/arduino/avr-libc/realloc.d

.build/mega2560/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc   -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/mega2560/arduino/wiring_shift.d






.build/mega2560/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/mega2560/arduino/WMath.d

.build/mega2560/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/mega2560/arduino/CDC.d

.build/mega2560/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/mega2560/arduino/new.d

.build/mega2560/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/mega2560/arduino/WString.d

.build/mega2560/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/mega2560/arduino/IPAddress.d

.build/mega2560/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/mega2560/arduino/Print.d

.build/mega2560/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/mega2560/arduino/HardwareSerial.d

.build/mega2560/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/mega2560/arduino/Tone.d

.build/mega2560/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/mega2560/arduino/main.d

.build/mega2560/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/mega2560/arduino/USBCore.d

.build/mega2560/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/mega2560/arduino/Stream.d

.build/mega2560/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/mega2560/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/mega2560/arduino/HID.d



.build/mega2560/arduino/libarduino.a : .build/mega2560/arduino/wiring.o .build/mega2560/arduino/wiring_digital.o .build/mega2560/arduino/wiring_analog.o .build/mega2560/arduino/WInterrupts.o .build/mega2560/arduino/wiring_pulse.o .build/mega2560/arduino/avr-libc/malloc.o .build/mega2560/arduino/avr-libc/realloc.o .build/mega2560/arduino/wiring_shift.o .build/mega2560/arduino/WMath.o .build/mega2560/arduino/CDC.o .build/mega2560/arduino/new.o .build/mega2560/arduino/WString.o .build/mega2560/arduino/IPAddress.o .build/mega2560/arduino/Print.o .build/mega2560/arduino/HardwareSerial.o .build/mega2560/arduino/Tone.o .build/mega2560/arduino/main.o .build/mega2560/arduino/USBCore.o .build/mega2560/arduino/Stream.o .build/mega2560/arduino/HID.o
	@echo [92mLinking libarduino.a[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/mega2560/src/ultralcd.o : src/ultralcd.cpp
	@echo [93msrc/ultralcd.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/ultralcd.cpp
include .build/mega2560/src/ultralcd.d

.build/mega2560/src/SdBaseFile.o : src/SdBaseFile.cpp
	@echo [93msrc/SdBaseFile.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/SdBaseFile.cpp
include .build/mega2560/src/SdBaseFile.d

.build/mega2560/src/SdFile.o : src/SdFile.cpp
	@echo [93msrc/SdFile.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/SdFile.cpp
include .build/mega2560/src/SdFile.d

.build/mega2560/src/LiquidCrystalRus.o : src/LiquidCrystalRus.cpp
	@echo [93msrc/LiquidCrystalRus.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/LiquidCrystalRus.cpp
include .build/mega2560/src/LiquidCrystalRus.d

.build/mega2560/src/watchdog.o : src/watchdog.cpp
	@echo [93msrc/watchdog.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/watchdog.cpp
include .build/mega2560/src/watchdog.d

.build/mega2560/src/SdVolume.o : src/SdVolume.cpp
	@echo [93msrc/SdVolume.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/SdVolume.cpp
include .build/mega2560/src/SdVolume.d

.build/mega2560/src/Servo.o : src/Servo.cpp
	@echo [93msrc/Servo.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/Servo.cpp
include .build/mega2560/src/Servo.d

.build/mega2560/src/ConfigurationStore.o : src/ConfigurationStore.cpp
	@echo [93msrc/ConfigurationStore.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/ConfigurationStore.cpp
include .build/mega2560/src/ConfigurationStore.d

.build/mega2560/src/digipot_mcp4451.o : src/digipot_mcp4451.cpp
	@echo [93msrc/digipot_mcp4451.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/digipot_mcp4451.cpp
include .build/mega2560/src/digipot_mcp4451.d

.build/mega2560/src/BlinkM.o : src/BlinkM.cpp
	@echo [93msrc/BlinkM.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/BlinkM.cpp
include .build/mega2560/src/BlinkM.d

.build/mega2560/src/vector_3.o : src/vector_3.cpp
	@echo [93msrc/vector_3.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/vector_3.cpp
include .build/mega2560/src/vector_3.d

.build/mega2560/src/temperature.o : src/temperature.cpp
	@echo [93msrc/temperature.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/temperature.cpp
include .build/mega2560/src/temperature.d

.build/mega2560/src/motion_control.o : src/motion_control.cpp
	@echo [93msrc/motion_control.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/motion_control.cpp
include .build/mega2560/src/motion_control.d

.build/mega2560/src/cardreader.o : src/cardreader.cpp
	@echo [93msrc/cardreader.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/cardreader.cpp
include .build/mega2560/src/cardreader.d

.build/mega2560/src/stepper.o : src/stepper.cpp
	@echo [93msrc/stepper.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/stepper.cpp
include .build/mega2560/src/stepper.d

.build/mega2560/src/qr_solve.o : src/qr_solve.cpp
	@echo [93msrc/qr_solve.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/qr_solve.cpp
include .build/mega2560/src/qr_solve.d

.build/mega2560/src/Marlin_main.o : src/Marlin_main.cpp
	@echo [93msrc/Marlin_main.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/Marlin_main.cpp
include .build/mega2560/src/Marlin_main.d

.build/mega2560/src/MarlinSerial.o : src/MarlinSerial.cpp
	@echo [93msrc/MarlinSerial.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/MarlinSerial.cpp
include .build/mega2560/src/MarlinSerial.d

.build/mega2560/src/planner.o : src/planner.cpp
	@echo [93msrc/planner.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/planner.cpp
include .build/mega2560/src/planner.d

.build/mega2560/src/SdFatUtil.o : src/SdFatUtil.cpp
	@echo [93msrc/SdFatUtil.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/SdFatUtil.cpp
include .build/mega2560/src/SdFatUtil.d

.build/mega2560/src/Marlin.o : src/Marlin.cpp
	@echo [93msrc/Marlin.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/Marlin.cpp
include .build/mega2560/src/Marlin.d

.build/mega2560/src/Sd2Card.o : src/Sd2Card.cpp
	@echo [93msrc/Sd2Card.cpp[0m
	@mkdir -p .build/mega2560/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=105 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c src/Sd2Card.cpp
include .build/mega2560/src/Sd2Card.d







.build/mega2560/firmware.elf : .build/mega2560/src/ultralcd.o .build/mega2560/src/SdBaseFile.o .build/mega2560/src/SdFile.o .build/mega2560/src/LiquidCrystalRus.o .build/mega2560/src/watchdog.o .build/mega2560/src/SdVolume.o .build/mega2560/src/Servo.o .build/mega2560/src/ConfigurationStore.o .build/mega2560/src/digipot_mcp4451.o .build/mega2560/src/BlinkM.o .build/mega2560/src/vector_3.o .build/mega2560/src/temperature.o .build/mega2560/src/motion_control.o .build/mega2560/src/cardreader.o .build/mega2560/src/stepper.o .build/mega2560/src/qr_solve.o .build/mega2560/src/Marlin_main.o .build/mega2560/src/MarlinSerial.o .build/mega2560/src/planner.o .build/mega2560/src/SdFatUtil.o .build/mega2560/src/Marlin.o .build/mega2560/src/Sd2Card.o .build/mega2560/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega2560 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/mega2560/firmware.hex : .build/mega2560/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/mega2560/src/dependencies.d .build/mega2560/arduino/dependencies.d

all : .build/mega2560/firmware.hex
	@true

